# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build for testing"
  lane :build_for_testing do
    scan(
      workspace: "Facio.xcworkspace",
      scheme: "Facio",
      derived_data_path: "derivedData",
      build_for_testing: true
    )
  end

  desc "Run unit test"
  lane :unit_test do
    scan(
      workspace: "Facio.xcworkspace",
      scheme: "Facio",
      only_testing: ["FacioTests"],
      derived_data_path: "derivedData",
      test_without_building: true
    )
  end

  desc "Run UI test"
  lane :ui_test do
    scan(
      workspace: "Facio.xcworkspace",
      scheme: "Facio",
      only_testing: ["FacioUITests"],
      derived_data_path: "derivedData",
      test_without_building: true,
      devices: ["iPhone 12"]
    )
  end

  desc "Increase build version"
  lane :increment_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV['FIREBASE_APP_ID']
    )
    increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
  end

  desc "Upload to firebase app distribution"
  lane :upload_to_firebase do
    build_app(
      workspace: "Facio.xcworkspace",
      scheme: "Facio",
      silent: true,
      export_options: {
        method: "development"
      }
    )

    increment_version
    
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      groups: "testers",
      release_notes: "Release staging",
      firebase_cli_token: ENV['FIREBASE_TOKEN']
    )
  end
end
